### ISSUE TITLE
How to select Nord in Guake?

### ISSUE THREAD

**Issue by Vistaus** [arcticicestudio/nord-guake#3] opened 2017-05-27 09:46 UTC
I've used the script to install Nord for Guake and it reports that it has installed successfully. But I can't choose Nord or Aurora (I really want the Aurora color scheme!) in the Guake preferences.

How do I do this?

OS: Solus (Linux)
DE: Budgie
Nord-Guake: latest Git Master

**Comment by arcticicestudio** [comment] 2017-05-31 03:50
Which Guake version  are you running? This may be related to the Nord GNOME Terminal project which had some problems due to the new `dconf` usage in the latest version.

**Comment by Vistaus** [comment] 2017-05-31 08:31
I'm using the latest version of Guake, 0.8.9: https://github.com/Guake/guake/releases/tag/0.8.9

**Comment by arcticicestudio** [comment] 2017-07-08 15:53
@Vistaus Sorry for my late reply, I've been busy with my job.
I've tried to reproduce this, but it works fine and all colors have been set.
**Please note that the theme won't appear as selectable theme in the dropdown menu since these themes are hardcoded and Guake has no way to provide custom themes!**

The script will set the colors as "Custom" theme, but as soon as you select another theme from the downdown menu it will be overriden and you'll have to execute the script again.

**Comment by arcticicestudio** [comment] 2017-09-23 17:02
@Vistaus Have you been able to get it working? Unfortunately there is no way (or I've not found it in the documentation) to easily add themes, the Guake team should definitely improve this.

I'll close this issue for now since the selection behavior is intended by Guake, feel free to reopen if there are still problems :smile:

**Closed as completed** 2017-10-01 13:35 UTC
Labels: type-support, resolution-by-design
